begin;select plan(18);
select has_table('public','production_batches','batches exist');
select has_table('public','production_batch_allocations','allocations exist');
select has_table('public','order_fulfillment_items','fulfillment exists');
select has_table('public','production_incidents','incidents exist');
select has_function('public','generate_production_batches',array['date'],'generator exists');
select has_function('public','reconcile_production',array['date'],'reconciliation exists');
select has_function('public','update_production_batch',array['uuid','integer','integer','public.production_batch_status','text','timestamp with time zone'],'optimistic batch update exists');
select has_function('public','set_order_fulfillment_status',array['uuid','public.order_status','text'],'guarded order transition exists');
select col_is_unique('public','order_fulfillment_items','order_item_id','one fulfillment per order line');
select ok((select exists(select 1 from pg_indexes where schemaname='public' and tablename='production_batches' and indexdef like '%production_date, product_variant_id%')),'batch identity is unique');
select ok((select relrowsecurity from pg_class where oid='public.production_batches'::regclass),'batch RLS');
select ok((select relrowsecurity from pg_class where oid='public.production_incidents'::regclass),'incident RLS');
select is((select count(*)::integer from public.app_settings where key in('production.batch_generation_days_ahead','production.stale_ready_order_hours','production.reconciliation_interval')),3,'commercial job values are configured');
set local role authenticated;select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',true);
select throws_ok($$select public.generate_production_batches(current_date)$$,'42501',null,'customer cannot generate');
select throws_ok($$select public.adjust_production_batch(gen_random_uuid(),1,'test')$$,'42501',null,'customer cannot adjust');
select throws_ok($$select public.run_production_jobs()$$,'42501',null,'customer cannot run jobs');
select ok(position('payment_status=''paid''' in pg_get_functiondef('public.generate_production_batches(date)'::regprocedure))>0,'only paid orders feed production');
select ok(position('pg_advisory_xact_lock' in pg_get_functiondef('public.generate_production_batches(date)'::regprocedure))>0,'concurrent generation is locked');
select * from finish();rollback;
